### ISSUE TITLE
jupyter taceback

### ISSUE THREAD

**Issue by Cherkah** [jupyter/jupyter_core#128]
why got i this traceback:

```
Traceback (most recent call last):
  File "/usr/bin/jupyter-notebook", line 11, in <module> load_entry_point('notebook==5.4.0', 'console_scripts', 'jupyter-notebook')()

   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 587, in load_entry_point return get_distribution(dist).load_entry_point(group, name)

  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2800, in load_entry_point return ep.load()

  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2431, in load return self.resolve()

  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2437, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)

  File "/usr/lib/python3/dist-packages/notebook/notebookapp.py", line 45, in <module> ioloop.install()

  File "/usr/lib/python3/dist-packages/zmq/eventloop/ioloop.py", line 210, in install assert (not ioloop.IOLoop.initialized()) or \

AttributeError: type object 'IOLoop' has no attribute 'initialized'`
```

i'm on debian testing with a jupyter's instal via repository

regards

**Comment by Cherkah** [comment]
right now, my python3-zmq version give 16.0.2-2+b1.
i've to wait for the 17 one (repo version) to play with jupyter-notebook on debian!
thx

**Comment by takluyver** [comment]
Or install pyzmq using pip or conda. If Debian has packaged tornado 5 but not pyzmq 17, then complain to Debian about it - we don't control Debian packages.

**Comment by takluyver** [comment]
Great :-)
