### ISSUE TITLE
ImportError: DLL load failed: %1 is not a valid Win32 application.

### ISSUE THREAD

**Issue by SibusisoGin** [jupyter/jupyter_core#219]
Can anyone help on this?

(2_7env) D:\NDMA\scripts>python STEP_0101_read_hdf_create_LST_anom_netcdf.py
Traceback (most recent call last):
  File "STEP_0101_read_hdf_create_LST_anom_netcdf.py", line 5, in <module>
    from libs.subgrid_calculations import HDFSubGrid
  File "D:\NDMA\scripts\libs\subgrid_calculations.py", line 211, in <module>
    class HDFSubGrid:
  File "D:\NDMA\scripts\libs\subgrid_calculations.py", line 212, in HDFSubGrid
    import libs.hdf_functions as HDF
  File "D:\NDMA\scripts\libs\hdf_functions.py", line 2, in <module>
    from pyhdf.SD import SD, SDC
  File "C:\Users\NDMA-GIS\Anaconda2\envs\2_7env\lib\site-packages\pyhdf\SD.py", line 1004, in <module>
    from . import hdfext as _C
  File "C:\Users\NDMA-GIS\Anaconda2\envs\2_7env\lib\site-packages\pyhdf\hdfext.py", line 28, in <module>
    _hdfext = swig_import_helper()
  File "C:\Users\NDMA-GIS\Anaconda2\envs\2_7env\lib\site-packages\pyhdf\hdfext.py", line 24, in swig_import_helper
    _mod = imp.load_module('_hdfext', fp, pathname, description)
ImportError: DLL load failed: %1 is not a valid Win32 application.

**Comment by kevin-bates** [comment]
Please take a look at some of the solutions/workarounds in #187.  Closing as duplicate.
