### ISSUE TITLE
ModuleNotFoundError: No module named 'jupyter_core'

### ISSUE THREAD

**Issue by arunhpatil** [jupyter/jupyter_core#295]
Hi I had installed jupyterlab with Conda, and it was working fine until recently. I can't correct an issue after I started installing R, something somewhere is messed up. 

```
$jupyter-lab
Traceback (most recent call last):
  File "/home/arun/.local/bin/jupyter-lab", line 5, in <module>
    from jupyterlab.labapp import main
  File "/home/arun/.local/lib/python3.8/site-packages/jupyterlab/labapp.py", line 11, in <module>
    from jupyter_core.application import JupyterApp, NoStart, base_aliases, base_flags
ModuleNotFoundError: No module named 'jupyter_core'
```

I tried this: 
```
$ conda install -c conda-forge jupyter_core
/home/arun/.local/lib/python3.8/site-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.11) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

Retrieving notices: ...working... done
```

I also tried this: 
```
$ pip3.8 install jupyter_core
Traceback (most recent call last):
  File "/home/arun/miniconda3/bin/pip3.8", line 5, in <module>
    from pip._internal.cli.main import main
  File "/home/arun/miniconda3/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/home/arun/miniconda3/lib/python3.8/site-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/home/arun/miniconda3/lib/python3.8/site-packages/pip/_internal/cli/main_parser.py", line 8, in <module>
    from pip._internal.cli import cmdoptions
  File "/home/arun/miniconda3/lib/python3.8/site-packages/pip/_internal/cli/cmdoptions.py", line 24, in <module>
    from pip._internal.cli.parser import ConfigOptionParser
  File "/home/arun/miniconda3/lib/python3.8/site-packages/pip/_internal/cli/parser.py", line 12, in <module>
    from pip._internal.configuration import Configuration, ConfigurationError
  File "/home/arun/miniconda3/lib/python3.8/site-packages/pip/_internal/configuration.py", line 26, in <module>
    from pip._internal.utils.logging import getLogger
  File "/home/arun/miniconda3/lib/python3.8/site-packages/pip/_internal/utils/logging.py", line 29, in <module>
    from pip._internal.utils.misc import ensure_dir
  File "/home/arun/miniconda3/lib/python3.8/site-packages/pip/_internal/utils/misc.py", line 42, in <module>
    from pip._internal.locations import get_major_minor_version
  File "/home/arun/miniconda3/lib/python3.8/site-packages/pip/_internal/locations/__init__.py", line 14, in <module>
    from . import _sysconfig
  File "/home/arun/miniconda3/lib/python3.8/site-packages/pip/_internal/locations/_sysconfig.py", line 11, in <module>
    from .base import change_root, get_major_minor_version, is_osx_framework
  File "/home/arun/miniconda3/lib/python3.8/site-packages/pip/_internal/locations/base.py", line 16, in <module>
    site_packages: typing.Optional[str] = sysconfig.get_path("purelib")
  File "/home/arun/miniconda3/lib/python3.8/sysconfig.py", line 521, in get_path
    return get_paths(scheme, vars, expand)[name]
  File "/home/arun/miniconda3/lib/python3.8/sysconfig.py", line 511, in get_paths
    return _expand_vars(scheme, vars)
  File "/home/arun/miniconda3/lib/python3.8/sysconfig.py", line 172, in _expand_vars
    _extend_dict(vars, get_config_vars())
  File "/home/arun/miniconda3/lib/python3.8/sysconfig.py", line 559, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/home/arun/miniconda3/lib/python3.8/sysconfig.py", line 430, in _init_posix
    _temp = __import__(name, globals(), locals(), ['build_time_vars'], 0)
ModuleNotFoundError: No module named '_sysconfigdata_x86_64_conda_cos7_linux_gnu'
```

I also raised an issue in Conda, [issue-1392979472](https://github.com/conda-forge/python-feedstock/issues/584#issue-1392979472). I have given more system info there, but if you need any additional information, please let me know. 

I tried this too:
$jupyter
```
Traceback (most recent call last):
  File "/home/arun/miniconda3/bin/jupyter", line 11, in <module>
    sys.exit(main())
  File "/home/arun/miniconda3/lib/python3.8/site-packages/jupyter_core/command.py", line 319, in main
    parser.print_help(file=sys.stderr)
  File "/home/arun/miniconda3/lib/python3.8/argparse.py", line 2494, in print_help
    self._print_message(self.format_help(), file)
  File "/home/arun/miniconda3/lib/python3.8/argparse.py", line 2475, in format_help
    formatter.add_text(self.epilog)
  File "/home/arun/miniconda3/lib/python3.8/site-packages/jupyter_core/command.py", line 30, in epilog
    return "Available subcommands: %s" % " ".join(list_subcommands())
  File "/home/arun/miniconda3/lib/python3.8/site-packages/jupyter_core/command.py", line 73, in list_subcommands
    for d in _path_with_self():
  File "/home/arun/miniconda3/lib/python3.8/site-packages/jupyter_core/command.py", line 151, in _path_with_self
    bindir = sysconfig.get_path("scripts")
  File "/home/arun/miniconda3/lib/python3.8/sysconfig.py", line 521, in get_path
    return get_paths(scheme, vars, expand)[name]
  File "/home/arun/miniconda3/lib/python3.8/sysconfig.py", line 511, in get_paths
    return _expand_vars(scheme, vars)
  File "/home/arun/miniconda3/lib/python3.8/sysconfig.py", line 172, in _expand_vars
    _extend_dict(vars, get_config_vars())
  File "/home/arun/miniconda3/lib/python3.8/sysconfig.py", line 559, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/home/arun/miniconda3/lib/python3.8/sysconfig.py", line 430, in _init_posix
    _temp = __import__(name, globals(), locals(), ['build_time_vars'], 0)
ModuleNotFoundError: No module named '_sysconfigdata_x86_64_conda_cos7_linux_gnu'
```

I am using Ubuntu 18 on WSL.

**Comment by minrk** [comment]
Thus is unlikely to be related to any jupyter package, but rather a broken conda environment (sysconfig, which is part of Python itself, is not working. jupyter-core just happens to be what's importing the broken standard library). I'm not sure if there's an easier fix than creating a fresh conda env.

**Comment by arunhpatil** [comment]
@minrk, 

Thank you for your response. I am unable to create a new environment on my WSL as well (error message below), something is messed up and I don't know how to resolve this. Currently, I have some projects that is expected to finish soon, and once that is done, I will reinstall all related software or WSL itself. In the meantime, I have installed anaconda on windows and will use that temporarily.  

```

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/arun/miniconda3/lib/python3.8/site-packages/conda/gateways/connection/session.py", line 59, in __call__
        return cls._thread_local.session
    AttributeError: '_thread._local' object has no attribute 'session'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/arun/miniconda3/lib/python3.8/site-packages/conda/exceptions.py", line 1129, in __call__
        return func(*args, **kwargs)
      File "/home/arun/miniconda3/lib/python3.8/site-packages/conda/cli/main.py", line 86, in main_subshell
        exit_code = do_call(args, p)
      File "/home/arun/miniconda3/lib/python3.8/site-packages/conda/cli/conda_argparse.py", line 93, in do_call
        return getattr(module, func_name)(args, parser)
      File "/home/arun/miniconda3/lib/python3.8/site-packages/conda/notices/core.py", line 72, in wrapper
        return_value = func(*args, **kwargs)
      File "/home/arun/miniconda3/lib/python3.8/site-packages/conda/cli/main_create.py", line 43, in execute
        install(args, parser, 'create')
      File "/home/arun/miniconda3/lib/python3.8/site-packages/conda/cli/install.py", line 261, in install
        unlink_link_transaction = solver.solve_for_transaction(
      File "/home/arun/miniconda3/lib/python3.8/site-packages/conda/core/solve.py", line 165, in solve_for_transaction
        self._notify_conda_outdated(link_precs)
      File "/home/arun/miniconda3/lib/python3.8/site-packages/conda/core/solve.py", line 1012, in _notify_conda_outdated
        SubdirData.query_all(conda_newer_spec, self.channels, self.subdirs,
      File "/home/arun/miniconda3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 137, in query_all
        result = tuple(concat(executor.map(subdir_query, channel_urls)))
      File "/home/arun/miniconda3/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
        yield fs.pop().result()
      File "/home/arun/miniconda3/lib/python3.8/concurrent/futures/_base.py", line 444, in result
        return self.__get_result()
      File "/home/arun/miniconda3/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
        raise self._exception
      File "/home/arun/miniconda3/lib/python3.8/concurrent/futures/thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/home/arun/miniconda3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 129, in <lambda>
        subdir_query = lambda url: tuple(SubdirData(Channel(url), repodata_fn=repodata_fn).query(
      File "/home/arun/miniconda3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 142, in query
        self.load()
      File "/home/arun/miniconda3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 207, in load
        _internal_state = self._load()
      File "/home/arun/miniconda3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 277, in _load
        raw_repodata_str = fetch_repodata_remote_request(
      File "/home/arun/miniconda3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 513, in fetch_repodata_remote_request
        session = CondaSession()
      File "/home/arun/miniconda3/lib/python3.8/site-packages/conda/gateways/connection/session.py", line 61, in __call__
        session = cls._thread_local.session = super(CondaSessionType, cls).__call__()
      File "/home/arun/miniconda3/lib/python3.8/site-packages/conda/gateways/connection/session.py", line 83, in __init__
        retry = Retry(total=context.remote_max_retries,
    TypeError: __init__() got an unexpected keyword argument 'raise_on_status'
```

Thank you,
Arun.

**Comment by ivanov** [comment]
Closing this - per resolution in https://github.com/conda-forge/python-feedstock/issues/584#issue-1392979472
