### ISSUE TITLE
OSError: [Errno None not found] 2 with 'notebook --generate-config'

### ISSUE THREAD

**Issue by NiklasRosenstein** [jupyter/jupyter_core#93]
```
niklas@DESKTOP-RQTQ13S MINGW64 ~/Desktop
$ jupyter notepad --generate-config
Traceback (most recent call last):
  File "c:\python35-32\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python35-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python35-32\Scripts\jupyter.exe\__main__.py", line 9, in <module>
  File "c:\python35-32\lib\site-packages\jupyter_core\command.py", line 186, in main
    _execvp(command, sys.argv[1:])
  File "c:\python35-32\lib\site-packages\jupyter_core\command.py", line 104, in _execvp
    raise OSError('%r not found' % cmd, errno.ENOENT)
OSError: [Errno None not found] 2
```

Jupyter Version 4.2.0  
Windows 10 x64, Git-For-Windows Bash  
Python 3.5.2 32-Bit

**Comment by takluyver** [comment]
It's `notebook`, not `notepad` ;-)

The unhelpful 'None not found' error is a bug in jupyter_core, which should be fixed when a new release occurs.

**Comment by NiklasRosenstein** [comment]
Ups, of course! Works now ;-)
